[package]
name = "yarp2-codegen"
version = "0.1.0"
authors = ["Samuel Moriarty <insomnia.array@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.5"
serde = "1.0.82"
serde_derive = "1.0.82"
heck = "0.3.1"
itertools = "0.8.0"
