[package]
name = "yarp2-codegen"
version = "0.1.0"
authors = ["Timofey Sokolov <insomnia.array@gmail.com>"]

[dependencies]
csv = "1.0"
serde = "1.0"
serde_derive = "1.0"
heck = "0.3"
itertools = "0.7.3"